add
vlau26/WebEventFinder pull request #5
Opened 2019-08-06 16:46 UTC by mdoam

2019-08-06 19:43 UTC, vlau26 requested changes
minor changes regarding namespace names only. 👍  then for me it's ready to merge !

2019-08-06 19:43 UTC, vlau26 commented on CartApi/Infrastructure/ActionResults/InternalServerErrorObjectResult.cs
> +namespace ShoesOnContainers.Services.CartApi.Infrastructure.ActionResults
```suggestion
namespace EventBriteAssignment.Services.CartApi.Infrastructure.ActionResults
```
change namespace name, should match with Rebka's namespace name change too

2019-08-06 19:43 UTC, vlau26 commented on CartApi/Infrastructure/Exceptions/CartDomainException.cs
> +namespace ShoesOnContainers.Services.CartApi.Infrastructure.Exceptions
```suggestion
namespace EventBriteAssignment.Services.CartApi.Infrastructure.Exceptions
```
change namespace name

2019-08-06 19:43 UTC, vlau26 commented on CartApi/Infrastructure/Filters/HttpGlobalExceptionFilter.cs
> +using ShoesOnContainers.Services.CartApi.Infrastructure.ActionResults;
once namespace names are changed, update here to include the appropriate namespace. Lines 2, 3 and line 10

2019-08-06 19:43 UTC, vlau26 commented on CartApi/Messaging/Consumers/OrderCompletedEventConsumer.cs
> +using ShoesOnContainers.Services.CartApi.Model;
namespace name change

2019-08-06 19:43 UTC, vlau26 commented on CartApi/Model/Cart.cs
> +namespace ShoesOnContainers.Services.CartApi.Model
namespace name change

2019-08-06 19:43 UTC, vlau26 commented on CartApi/Model/Cart.cs
> +            Events = new List<Model.CartItem>();
```suggestion
            Events = new List<CartItem>();
```
I believe 'Model. ' is not needed if namespace is correct

2019-08-06 19:43 UTC, vlau26 commented on CartApi/Model/CartItem.cs
> +namespace ShoesOnContainers.Services.CartApi.Model
update namespace name

2019-08-07 20:13 UTC, mdoam reviewed
Hi all, I've changed namespace to appropriate name. Let me know if the codes are ready to merge.

2019-08-07 23:52 UTC, vlau26 approved these changes
I'm good with you merging it after Rebka or Sunny reviews and approves. 👍

2019-08-08 18:19 UTC, parks38 commented
The code seems good to merge!

2019-08-08 18:22 UTC, merged